### ISSUE TITLE
ReferenceError: window is not defined - on Meteor 1.1.0.2

### ISSUE THREAD

**Issue by BFR33** [kenlimmj/meteor-hljs#1]
I just added the package and meteor just started vomiting out this error message:
```
W20150603-22:30:31.355(2)? (STDERR)           
W20150603-22:30:31.356(2)? (STDERR) /home/*****/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150603-22:30:31.356(2)? (STDERR) 						throw(ex);
W20150603-22:30:31.357(2)? (STDERR) 						      ^
W20150603-22:30:31.357(2)? (STDERR) ReferenceError: window is not defined
W20150603-22:30:31.357(2)? (STDERR)     at t (packages/kenlimmj:hljs/highlight.pack.js:1:1)
W20150603-22:30:31.357(2)? (STDERR)     at Package (packages/kenlimmj:hljs/highlight.pack.js:1:1)
W20150603-22:30:31.357(2)? (STDERR)     at /home/*****/meteor/test2/.meteor/local/build/programs/server/packages/kenlimmj_hljs.js:21:4
W20150603-22:30:31.357(2)? (STDERR)     at /home/*****/meteor/test2/.meteor/local/build/programs/server/packages/kenlimmj_hljs.js:30:3
W20150603-22:30:31.357(2)? (STDERR)     at /home/*****/meteor/test2/.meteor/local/build/programs/server/boot.js:222:10
W20150603-22:30:31.357(2)? (STDERR)     at Array.forEach (native)
W20150603-22:30:31.357(2)? (STDERR)     at Function._.each._.forEach (/home/*****/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150603-22:30:31.357(2)? (STDERR)     at /home/*****/meteor/test2/.meteor/local/build/programs/server/boot.js:117:5
=> Exited with code: 8
```

The problem is, I think, that the server doesn't has a `window` object.
Since `hljs` isn't needen on the server, a simple `if (window||false) {...}` should be enough...

**Comment by kenlimmj** [comment]
Was able to reproduce this successfully. Meteor updated the package API since this was published and it's my fault for failing to keep this current. 

It also seems like the problem is a little more deeply rooted than Highlight.js running on the server side and failing to find a window object - a simple fix for that would be to just set:

```js
Package.onUse(function(api) {
  api.versionsFrom('1.1.0.2');
  api.add_files('highlight.pack.js', 'client');
  api.export('hljs', 'client');
```
but when I tried that, a bunch of other errors popped up. They look like they're caused by conflicting namespaces, but I think I'll have a fix very soon.

The reason for wanting Highlight.js to run both on the client and server is because sometimes people could run say, a Markdown parser with inbuilt highlighting via a method hooked to their collection's CRUD operations.
